### ISSUE TITLE
Error in running tukey_hsd

### ISSUE THREAD

**Issue by pavitraviswanath** [jbengler/tidyplots#7] opened 2024-11-20 21:41 UTC
Hello! Thank you for a great package. I have 4 groups in which I am trying to run a Tukey multiple comparison analysis. However I get the following error even when I use the example data:

```
> gene_expression %>% 
+     # filter to one gene
+     dplyr::filter(external_gene_name == "Apol6") %>% 
+     # start plotting
+     tidyplot(x = condition, y = expression, color = sample_type) %>% 
+     add_mean_dash() %>% 
+     add_sem_errorbar() %>% 
+     add_data_points() %>% 
+     add_test_pvalue(method="tukey_hsd")
Warning message:
Computation failed in `stat_pwc()`.
Caused by error in `mutate()`:
ℹ In argument: `data = map(.data$data, .f, ...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `TukeyHSD.aov()`:
! no factors in the fitted model 
> study %>% 
+     tidyplot(x = treatment, y = score, color = treatment) %>% 
+     add_mean_dash() %>% 
+     add_sem_errorbar() %>% 
+     add_data_points() %>% 
+     add_test_pvalue(method = "tukey_hsd")
Warning message:
p-values can't be adjusted by panel for the specified stat method.
The result of the method doesn't contain the p column.
Note that, tests such as tukey_hsd or games_howell_test handle p-value adjustement internally; they only return the p.adj. 
```

Normally, an anova is used to compute tukey_hsd but as that isn't run, what else can be done to run tukey_hsd add_test_pvalue? If we compute the p values using rstatix, is there a way to manually add those p values in tidyplots? Thank you for all your help!

**Comment by jbengler** [comment] 2024-11-20 23:15
Hi @pavitraviswanath 

Thank you for using tidyplots!

When I rewrite your first example to ggplot2 code, I get the exact same error. So, if this unexpected behavior, it is not coming from tidyplots, but rather `ggpubr::geom_pwc()`.

```
gene_expression %>% 
  dplyr::filter(external_gene_name == "Apol6") %>% 
  ggplot(aes(x = condition, y = expression, color = sample_type)) +
  geom_point(position = position_dodge(width = 0.8)) +
  ggpubr::geom_pwc(method="tukey_hsd")
```

However, it appears that the problem is coming from the color because it implies an additional layer of grouping. This works:

```
gene_expression %>% 
  dplyr::filter(external_gene_name == "Apol6") %>% 
  tidyplot(x = condition, y = expression) %>% 
  add_mean_dash() %>% 
  add_sem_errorbar() %>% 
  add_data_points() %>% 
  add_test_pvalue(method = "tukey_hsd", p.adjust.by = "group")

gene_expression %>% 
  dplyr::filter(external_gene_name == "Apol6") %>% 
  tidyplot(x = group, y = expression) %>% 
  add_mean_dash() %>% 
  add_sem_errorbar() %>% 
  add_data_points() %>% 
  add_test_pvalue(method = "tukey_hsd", p.adjust.by = "group")
``` 

Your second examples produces a plot but throws a warning. This can be fixed by providing `p.adjust.by = "group"`to `add_test_pvalue`

```
study %>% 
  tidyplot(x = treatment, y = score, color = treatment) %>% 
  add_mean_dash() %>% 
  add_sem_errorbar() %>% 
  add_data_points() %>% 
  add_test_pvalue(method = "tukey_hsd", p.adjust.by = "group")
```

The warning occurs because in `tidyplots::add_test_pvalue()` the default is `p.adjust.by = "panel"`, while the default in ggpubr::geom_pwc is `p.adjust.by = c("group", "panel")`.

To your last question. Tidyplots has no function to add ANOVA p values. However, you can do this by using the `add()` function to add ggplot2 code.

```
gene_expression %>% 
  dplyr::filter(external_gene_name == "Apol6") %>% 
  rstatix::anova_test(expression ~ group)

gene_expression %>% 
  dplyr::filter(external_gene_name == "Apol6") %>% 
  tidyplot(x = group, y = expression) %>% 
  add_mean_dash() %>% 
  add_sem_errorbar() %>% 
  add_data_points() %>% 
  adjust_padding(top = 0.1) %>% 
  add(ggpubr::stat_compare_means(method = "anova"))
```

Best
Jan

**Comment by pavitraviswanath** [comment] 2024-11-21 00:50
Thank you so much Jan! I was also trying to do something similar for this data but I am getting the error "Warning message:
Computation failed in `stat_pwc()`.
Caused by error in `mutate()`:
ℹ In argument: `data = map(.data$data, .f, ...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `TukeyHSD.aov()`:
! no factors in the fitted model " when I try to run tukey_hsd in my data. Here's the code of some sample data:

```
shRNA	group	log2FC
sh Scramble_ -IPTG	A	2.2
sh Scramble_ -IPTG	A	0.1
sh Scramble_ -IPTG	A	1.5
sh Scramble_ +IPTG	A	4
sh Scramble_ +IPTG	A	1.1
sh Scramble_ +IPTG	A	1
sh RNA_ -IPTG	A	4.2
sh RNA_ -IPTG	A	1.6
sh RNA_ -IPTG	A	0.8
sh RNA_ +IPTG	A	2.9
sh RNA_ +IPTG	A	0.8
sh RNA_ +IPTG	A	0.6
sh Scramble_ -IPTG	B	400
sh Scramble_ -IPTG	B	233
sh Scramble_ -IPTG	B	215
sh Scramble_ +IPTG	B	350
sh Scramble_ +IPTG	B	257.3
sh Scramble_ +IPTG	B	264.7
sh RNA_ -IPTG	B	333.8
sh RNA_ -IPTG	B	234.2
sh RNA_ -IPTG	B	257.6
sh RNA_ +IPTG	B	68.9
sh RNA_ +IPTG	B	90.1
sh RNA_ +IPTG	B	56.1

df %>%
  tidyplot(x = group, y = log2FC, color= shRNA) %>%
  add_mean_bar() %>%
  add_sem_errorbar() %>%
  add_data_points() %>%
  add_test_pvalue(method="tukey_hsd", p.adjust.by = "group", hide_info = TRUE) %>%
  adjust_size(100, 100) %>%
  adjust_colors(new_colors = colors_continuous_viridis) %>%
  adjust_x_axis_title("") %>%
  adjust_y_axis_title("$sfRon~Relative~Gene~Expression$") %>%
  theme_ggplot2()
```

Any feedback on how to get this to work with grouped data like this? Thank you so much for your help and such a great package!

**Comment by jbengler** [comment] 2024-11-21 08:54
Hard to say what you want to compare here. Something like this?

```
library(tidyverse)
library(tidyplots)

df <- 
  tribble(
  ~shRNA,	~group,	~log2FC,
  "sh Scramble_ -IPTG",	"A",	2.2,
  "sh Scramble_ -IPTG",	"A",	0.1,
  "sh Scramble_ -IPTG",	"A",	1.5,
  "sh Scramble_ +IPTG",	"A",	4,
  "sh Scramble_ +IPTG",	"A",	1.1,
  "sh Scramble_ +IPTG",	"A",	1,
  "sh RNA_ -IPTG",	"A",	4.2,
  "sh RNA_ -IPTG",	"A",	1.6,
  "sh RNA_ -IPTG",	"A",	0.8,
  "sh RNA_ +IPTG",	"A",	2.9,
  "sh RNA_ +IPTG",	"A",	0.8,
  "sh RNA_ +IPTG",	"A",	0.6,
  "sh Scramble_ -IPTG",	"B",	400,
  "sh Scramble_ -IPTG",	"B",	233,
  "sh Scramble_ -IPTG",	"B",	215,
  "sh Scramble_ +IPTG",	"B",	350,
  "sh Scramble_ +IPTG",	"B",	257.3,
  "sh Scramble_ +IPTG",	"B",	264.7,
  "sh RNA_ -IPTG",	"B",	333.8,
  "sh RNA_ -IPTG",	"B",	234.2,
  "sh RNA_ -IPTG",	"B",	257.6,
  "sh RNA_ +IPTG",	"B",	68.9,
  "sh RNA_ +IPTG",	"B",	90.1,
  "sh RNA_ +IPTG",	"B",	56.1
)

df %>%
  tidyplot(x = shRNA, y = log2FC, color= shRNA) %>%
  add_mean_bar() %>%
  add_sem_errorbar() %>%
  add_data_points() %>%
  add_test_pvalue(method="tukey_hsd", p.adjust.by = "group", hide_info = TRUE) %>%
  adjust_x_axis(rotate_labels = TRUE) %>% 
  split_plot(by = group, widths = 50, heights = 50)
```

**Comment by jbengler** [comment] 2024-11-21 08:57
By the way, please always provide example data in a format that can directly be used. For example by using the `tribble()` function (see above).

**Comment by pavitraviswanath** [comment] 2024-11-21 17:16
thank you! I've never used tribble (use datapasta) but that worked! What if I did not want to split the data into two plots? For example I am trying to create the below plot but I am unable to run tukey_hsd without it throwing an error:

```
df %>%
  tidyplot(x = group, y = log2FC, color= shRNA) %>%
  add_mean_bar() %>%
  add_sem_errorbar() %>%
  add_data_points() %>%
  add_test_pvalue(method="t.test", p.adjust.by = "group", hide_info = TRUE) %>%
  adjust_size(100, 100) %>%
  adjust_colors(new_colors = colors_continuous_viridis) %>%
  adjust_x_axis_title("") %>%
  adjust_y_axis_title("$sfRon~Relative~Gene~Expression$") %>%
  theme_ggplot2()
```
![image](https://github.com/user-attachments/assets/5d38bdf3-de21-45f8-9145-b7778816a6dc)

**Comment by jbengler** [comment] 2024-11-21 17:39
Please also provide the ggplot2 code, you used to generate the attached plot.

**Comment by pavitraviswanath** [comment] 2024-11-21 17:50
The plot is generated from this tidyplots code: :)

```
df %>%
  tidyplot(x = group, y = log2FC, color= shRNA) %>%
  add_mean_bar() %>%
  add_sem_errorbar() %>%
  add_data_points() %>%
  add_test_pvalue(method="t.test", p.adjust.by = "group", hide_info = TRUE) %>%
  adjust_size(100, 100) %>%
  adjust_colors(new_colors = colors_continuous_viridis) %>%
  adjust_x_axis_title("") %>%
  adjust_y_axis_title("$sfRon~Relative~Gene~Expression$") %>%
  theme_ggplot2()
```

**Closed as completed** 2024-11-21 21:30 UTC
